config/routes.rb
Rails.application.routes.draw do
  resources :trips

  devise_for :users
  root "pages#home"
  get "about" => "pages#about" # creates about_path
  get "createprofile" => "pages#createprofile" #creates createprofile_path

end

app/models/trip.rb
class Trip < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :trips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def createprofile
  end
  
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = current_user.trips.build
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = current_user.trips.build(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:fullname, :phonenumber, :date, :time, :origin, :destination)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RideShare", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
 
      <!--<form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>-->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
        <!--<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RideShare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!--mobile optimization -->
</head>
<body>
	
	<%= render 'layouts/header' %>
	<div>
		<% flash.each do |name, msg| %>
    	<%= content_tag(:div, msg, class: "alert alert-info") %>
    	<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<center><h1>About us</h1>
<p>This site was coded in 36 hours by Justin Tam, Tim Yu and Jacqualine Quach as part of Hack Camp, a subprogram under LA Hacks, that began on April 11 2014. Tim had no experience in Ruby or Ruby on Rails prior to this hackthon, and Jusitn and Jacqueline were both two weeks into their introduction to computer science course at UCLA. In other words....This site doesn't look bad for total newbs.</p>

<p> Honorary Mention: Darwin Ocampo , for at least attempting at learn Ruby. </p></center>

app/views/pages/home.html.erb
<div class="container1">	
	<div class="join center">
	<h1>Join RideShare </h1>

	<% if user_signed_in? %>
		<%= link_to "Create Trip", new_trip_path, :class => "btn btn-default btn-lg" %>
			<%= link_to "Browse Trips", trips_path, :class => "btn btn-primary btn-lg" %>
	<% else %>
		<p>	
			<%= link_to "Sign In", new_user_session_path, :class => "btn btn-default btn-lg" %>
			<%= link_to "Register", new_user_registration_path, :class => "btn btn-primary btn-lg" %>
		</p>
	<% end %>
</div>
</div>

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fullname %><br>
    <%= f.text_field :fullname %>
  </div>
  <div class="field">
    <%= f.label :phonenumber %><br>
    <%= f.text_field :phonenumber %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<div class="tripbkg">
  <div class="browsetrip center">
    <h1 color: "#ecf0f1">Trips</h1>
    <br />
    <table class="table">
     <thead>
      <tr>
        <th>Name</th>
        <th>Phone</th>
        <th>Date</th>
        <th>Time</th>
        <th>Origin</th>
        <th>Destination</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @trips.each do |trip| %>
        <tr>
          <td><%= trip.fullname %></td>
          <td><%= trip.phonenumber %></td>
          <td><%= trip.date %></td>
          <td><%= trip.time %></td>
          <td><%= trip.origin %></td>
          <td><%= trip.destination %></td>
          <% if trip.user == current_user %>
            <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
            <td><%= link_to 'delete', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>
<br>

app/views/trips/new.html.erb
<center><h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>
</center>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>
<center>
<p>
  <strong>Fullname:</strong>
  <%= @trip.fullname %>
</p>


  <strong>Phonenumber:</strong>
  <%= @trip.phonenumber %>
</p>

<p>
  <strong>Date:</strong>
  <%= @trip.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @trip.time %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @trip.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @trip.destination %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', root_path %>
></center>